const PortfolioData= [
    {
        id: 1,
        image: "images/port4.png",
        name: "Future Green Step",
        category: "MERN",
        description: "Project made in MERN using defferent technologies in it.",
        webLink: "https://futuregreensteps.com/",
    },
    {
        id: 23,
        image: "images/port23.png",
        name: "Jimmy choo",
        category: "MERN",
        description: "Project made in MERN using defferent technologies in it.",
        webLink: "https://futuregreensteps.com/",
    },
    {
        id: 24,
        image: "images/port24.png",
        name: "skylinx technologies",
        category: "MERN",
        description: "Project made in MERN using defferent technologies in it.",
        webLink: "https://skylinxtech.com/",
    },
    {
        id: 13,
        image: "images/port13.png",
        name: "Outfit Store",
        category: "ReactJs",
        description: "Project made in reactjs using defferent technologies in it.",
        webLink: "https://outfitstore.vercel.app/",
    },
    {
        id: 14,
        image: "images/port14.png",
        name: "bazaar",
        category: "ReactJs",
        description: "Project made in reactjs using defferent technologies in it.",
        webLink: "https://complete-bazar-ecom-website.vercel.app/",
    },
    {
        id: 15,
        image: "images/port15.png",
        name: "obrm zetz shop",
        category: "ReactJs",
        description: "Project made in reactjs using defferent technologies in it.",
        webLink: "https://obrm-zetz-shop.herokuapp.com/",
    },
    {
        id: 16,
        image: "images/port16.png",
        name: "rus digital",
        category: "ReactJs",
        description: "Project made in reactjs using defferent technologies in it.",
        webLink: "https://delightful-twilight-10e5bd.netlify.app/",
    },
    {
        id: 18,
        image: "images/port18.png",
        name: "shopping cart",
        category: "ReactJs",
        description: "Project made in reactjs using defferent technologies in it.",
        webLink: "https://react-shopping-cart-67954.firebaseapp.com/",
    },
    {
        id: 19,
        image: "images/port19.png",
        name: "admin dashboard",
        category: "ReactJs",
        description: "Project made in reactjs using defferent technologies in it.",
        webLink: "https://tasks-app-aridsm.netlify.app/",
    },
    {
        id: 20,
        image: "images/port20.png",
        name: "zishop",
        category: "nextJs",
        description: "Project made in nextJs using defferent technologies in it.",
        webLink: "https://e-commerce-onlineshop.vercel.app/",
    },
    {
        id: 21,
        image: "images/port21.png",
        name: "bagisto",
        category: "nextJs",
        description: "Project made in nextJs using defferent technologies in it.",
        webLink: "https://bagisto-commerce.vercel.app/",
    },
    {
        id: 25,
        image: "images/port25.png",
        name: "culture",
        category: "php",
        description: "Project made in php using defferent technologies in it.",
        webLink: "https://shopatculture.com/",
    },
    {
        id: 27,
        image: "images/port27.png",
        name: "master paints",
        category: "php",
        description: "Project made in php using defferent technologies in it.",
        webLink: "https://masterpaints.com/",
    },
    {
        id: 17,
        image: "images/port17.png",
        name: "edu life",
        category: "php",
        description: "Project made in php using defferent technologies in it.",
        webLink: "https://edulife.pk/",
    },
    {
        id: 2,
        image: "images/port1.png",
        name: "Clients & Community",
        category: "Wordpress",
        description: "Project made in Wordpress using defferent technologies in it.",
        webLink: "https://clientsandcommunity.com/",
    },
    {
        id: 26,
        image: "images/port26.png",
        name: "heathrow airport cabs",
        category: "Wordpress",
        description: "Project made in Wordpress using defferent technologies in it.",
        webLink: "https://heathrowairportcabs.co.uk/?gclid=CjwKCAjwpuajBhBpEiwA_ZtfhYvQiza7KxyWyhsYmSybIBirtTGpU44UxKk2LX3LQfqGUuruxbjpKhoCTVoQAvD_BwE",
    },
    {
        id: 3,
        image: "images/port2.png",
        name: "Bold Media",
        category: "Shopify",
        description: "Project made in Shopify using defferent technologies in it.",
        webLink: "https://boldmda.com/",
    },
    {
        id: 22,
        image: "images/port22.png",
        name: "mehver",
        category: "Shopify",
        description: "Project made in Shopify using defferent technologies in it.",
        webLink: "https://mehver.com/",
    },
    {
        id: 4,
        image: "images/port3.png",
        name: "Alpha group",
        category: "Wordpress",
        description: "Project made in Wordpress using defferent technologies in it.",
        webLink: "https://www.alphagroup.com/",
    },
    {
        id: 5,
        image: "images/port5.png",
        name: "superx.co",
        category: "Shopify",
        description: "Project made in Shopify using defferent technologies in it.",
        webLink: "https://www.superx.co/",
    },
    {
        id: 6,
        image: "images/port6.png",
        name: "Love Your Dog",
        category: "Shopify",
        description: "Project made in Shopify using defferent technologies in it.",
        webLink: "https://wynwooddogfood.com/",
    },
    {
        id: 7,
        image: "images/port7.png",
        name: "Weston Jewelers",
        category: "Wordpress",
        description: "Project made in Wordpress using defferent technologies in it.",
        webLink: "https://www.westonjewelers.com/",
    },
    {
        id: 8,
        image: "images/port8.png",
        name: "Hair We Share",
        category: "Wordpress",
        description: "Project made in Wordpress using defferent technologies in it.",
        webLink: "https://hairweshare.org/",
    },
    {
        id: 9,
        image: "images/port9.png",
        name: "Solar Energy",
        category: "MERN",
        description: "Project made in MERN using defferent technologies in it.",
        webLink: "https://www.hohmenergy.com/",
    },
    {
        id: 10,
        image: "images/port10.png",
        name: "Baby Script",
        category: "MERN",
        description: "Project made in MERN using defferent technologies in it.",
        webLink: "https://babyscripts.com/",
    },
    {
        id: 11,
        image: "images/port11.png",
        name: "Potion",
        category: "MERN",
        description: "Project made in MERN using defferent technologies in it.",
        webLink: "https://sendpotion.com/",
    },
    {
        id: 12,
        image: "images/port12.png",
        name: "You Preneur",
        category: "Wordpress",
        description: "Project made in Wordpress using defferent technologies in it.",
        webLink: "https://youpreneur.com/",
    },
    
    
    
    
]


export default PortfolioData;